# Default values for nocodb.

service:
  image:
    repository: "dbeaver/cloudbeaver"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "22.2.4"

global:
  postgresql:
    auth:
      username: "admin"
      password: "changeme"
      database: "cb-metadata"

postgresql:
  image:
    tag: "12"
  fullnameOverride: "cloudbeaver-db-0"

cloudbeaver: 
  serverName: "Cloudbeaver Server"
  
autodiscovery:
  postgres:
    port: 5432
    host: "postgresql-server"
    database: "defaultdb"
    user: "admin"
    password: "changeme"
  trino:
    port: 8080
    host: "trino-server"
    user: "admin"
    password: "changeme"
    
security:
  username: "onyxia"
  password: "password"
  maxLoginAttempts: 999
  networkPolicy: 
    enabled: false
    from: []
  allowlist:
    enabled: true
    ip: "0.0.0.0/0"  
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


networking:
  type: ClusterIP
  beaver:
    port: 8978
  service:
    port: 80
  

ingress:
  enabled: true
  tls: true
  ingressClassName: ""  
  annotations: []
    # kubernetes.io/tls-acme: "true"
  hostname: "chart-example.com"
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
